'use client';

import { motion, AnimatePresence } from 'framer-motion';
import { X, Download, ClipboardCheck, FileText, Camera } from 'lucide-react';
import type { RcaReport } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';

interface RcaModalProps {
  report: RcaReport | null;
  open: boolean;
  onClose: () => void;
}

export default function RcaModal({ report, open, onClose }: RcaModalProps) {
  if (!report) return null;

  const checklist = report.diagnostic_checklist || {};
  const checklistEntries = Object.entries(checklist);

  const handleDownloadPDF = () => {
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    if (!printWindow) { return; }

    const checklistHtml = checklistEntries.map(([key, value]) => {
      const passed = value === true || value === 'pass';
      return `<div style="display:flex;align-items:center;gap:12px;padding:10px 14px;border-radius:10px;background:#F7F7F5;border:1px solid #E8E4DF;margin-bottom:8px;">
        <div style="width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:600;${passed ? 'background:#FF5C00/20;color:#FF5C00' : 'background:#fee;color:#ef4444'}">${passed ? '✓' : '✗'}</div>
        <span style="font-size:14px;color:#1A1A1A;text-transform:capitalize">${key.replace(/_/g, ' ')}</span>
      </div>`;
    }).join('');

    const beforePhotosHtml = report.before_photos.length > 0 ? `
      <h3 style="font-size:14px;font-weight:600;margin:20px 0 10px">Before Photos</h3>
      <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px">
        ${report.before_photos.map((url, i) => `<img src="${url}" alt="Before ${i+1}" style="width:100%;border-radius:10px;border:1px solid #E8E4DF;aspect-ratio:1;object-fit:cover" />`).join('')}
      </div>` : '';

    const afterPhotosHtml = report.after_photos.length > 0 ? `
      <h3 style="font-size:14px;font-weight:600;margin:20px 0 10px">After Photos</h3>
      <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px">
        ${report.after_photos.map((url, i) => `<img src="${url}" alt="After ${i+1}" style="width:100%;border-radius:10px;border:1px solid #E8E4DF;aspect-ratio:1;object-fit:cover" />`).join('')}
      </div>` : '';

    printWindow.document.write(`<!DOCTYPE html><html><head><title>RCA Report</title>
      <style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;padding:30px;color:#1A1A1A}
      @media print{body{padding:20px}}</style></head><body>
      <div style="display:flex;align-items:center;gap:14px;margin-bottom:24px;border-bottom:2px solid #E8E4DF;padding-bottom:16px">
        <div style="width:44px;height:44px;border-radius:12px;background:#FFF0E6;display:flex;align-items:center;justify-content:center;font-size:20px">📋</div>
        <div><h1 style="margin:0;font-size:20px">RCA Report</h1><p style="margin:2px 0 0;font-size:12px;color:#999">Root Cause Analysis</p></div>
      </div>
      ${checklistEntries.length > 0 ? `<h3 style="font-size:14px;font-weight:600;margin-bottom:10px">Diagnostic Checklist</h3>${checklistHtml}` : ''}
      ${report.technician_notes ? `<h3 style="font-size:14px;font-weight:600;margin:20px 0 8px">Technician Notes</h3><p style="font-size:14px;color:#666;background:#F7F7F5;padding:14px;border-radius:10px;border:1px solid #E8E4DF;line-height:1.6">${report.technician_notes}</p>` : ''}
      ${beforePhotosHtml}${afterPhotosHtml}
      ${report.admin_notes ? `<h3 style="font-size:14px;font-weight:600;margin:20px 0 8px">Admin Notes</h3><p style="font-size:14px;color:#666;background:#F7F7F5;padding:14px;border-radius:10px;border:1px solid #E8E4DF">${report.admin_notes}</p>` : ''}
      <p style="text-align:center;color:#ccc;font-size:11px;margin-top:30px">Generated by CellCureHub • ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
    </body></html>`);
    printWindow.document.close();
    // Wait for images to load before printing
    setTimeout(() => { printWindow.print(); }, 500);
  };

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) onClose(); }}>
      <DialogContent className="sm:max-w-2xl max-h-[85vh] overflow-y-auto bg-white border-[#E8E4DF] text-[#1A1A1A]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-3 text-[#1A1A1A]">
            <div className="w-10 h-10 rounded-xl bg-[#FF5C00]/10 flex items-center justify-center shrink-0">
              <ClipboardCheck className="w-5 h-5 text-[#FF5C00]" />
            </div>
            <div>
              <span className="text-lg font-bold">RCA Report</span>
              <p className="text-xs text-[#1A1A1A]/40 font-normal">Root Cause Analysis</p>
            </div>
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6 mt-2">
          {/* Diagnostic Checklist */}
          {checklistEntries.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold text-[#1A1A1A] mb-3 flex items-center gap-2"><FileText className="w-4 h-4 text-[#FF5C00]" /> Diagnostic Checklist</h3>
              <div className="space-y-2">
                {checklistEntries.map(([key, value]) => (
                  <div key={key} className="flex items-center gap-3 p-3 rounded-xl bg-[#F7F7F5] border border-[#E8E4DF]">
                    <div className={`w-5 h-5 rounded-full flex items-center justify-center text-xs font-semibold ${value === true || value === 'pass' ? 'bg-[#FF5C00]/20 text-[#FF5C00]' : 'bg-red-500/20 text-red-500'}`}>
                      {value === true || value === 'pass' ? '✓' : '✗'}
                    </div>
                    <span className="text-sm text-[#1A1A1A]/70 capitalize">{key.replace(/_/g, ' ')}</span>
                    {typeof value === 'string' && value !== 'pass' && value !== 'fail' && (
                      <Badge variant="outline" className="ml-auto text-xs bg-white border-[#E8E4DF] text-[#1A1A1A]/60">{value}</Badge>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Technician Notes */}
          {report.technician_notes && (
            <div>
              <h3 className="text-sm font-semibold text-[#1A1A1A] mb-2">Technician Notes</h3>
              <p className="text-sm text-[#1A1A1A]/60 leading-relaxed bg-[#F7F7F5] rounded-xl p-4 border border-[#E8E4DF]">{report.technician_notes}</p>
            </div>
          )}

          {/* Before Photos */}
          {report.before_photos.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold text-[#1A1A1A] mb-3 flex items-center gap-2"><Camera className="w-4 h-4 text-[#FF5C00]" /> Before Photos</h3>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                {report.before_photos.map((url, i) => (
                  <a key={i} href={url} target="_blank" rel="noopener noreferrer" className="aspect-square rounded-xl overflow-hidden border border-[#E8E4DF] relative group block">
                    <img src={url} alt={`Before ${i + 1}`} className="w-full h-full object-cover group-hover:scale-105 transition-transform" />
                  </a>
                ))}
              </div>
            </div>
          )}

          {/* After Photos */}
          {report.after_photos.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold text-[#1A1A1A] mb-3 flex items-center gap-2"><Camera className="w-4 h-4 text-[#FF5C00]" /> After Photos</h3>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                {report.after_photos.map((url, i) => (
                  <a key={i} href={url} target="_blank" rel="noopener noreferrer" className="aspect-square rounded-xl overflow-hidden border border-[#E8E4DF] relative group block">
                    <img src={url} alt={`After ${i + 1}`} className="w-full h-full object-cover group-hover:scale-105 transition-transform" />
                  </a>
                ))}
              </div>
            </div>
          )}

          {/* Admin Notes */}
          {report.admin_notes && (
            <div>
              <h3 className="text-sm font-semibold text-[#1A1A1A] mb-2">Admin Notes</h3>
              <p className="text-sm text-[#1A1A1A]/60 bg-[#F7F7F5] rounded-xl p-4 border border-[#E8E4DF]">{report.admin_notes}</p>
            </div>
          )}

          {/* Download Button */}
          <Button onClick={handleDownloadPDF} className="w-full bg-[#FF5C00] hover:bg-[#FF5C00]/90 text-white font-semibold print:hidden">
            <Download className="w-4 h-4 mr-2" /> Download RCA as PDF
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
